---
- name: install ntp
  become: yes
  apt:
    update_cache: no
    state: present
    name: ntp

- name: ntp config file
  become: yes
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: restart ntp
...
